modLoader="javafml" #mandatory

loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="GNU Affero General Public License v3.0"

[[mods]] #mandatory

modId="affinity" #mandatory

version="1.19.2-0.0.2" #mandatory

displayName="Affinity Enchantment" #mandatory

logoFile="AffinityLogo.png" #optional

authors="Shutdoor" #optional

description='Gives the ability to mine faster in the air and in water.'

[[dependencies.affinity]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.affinity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
